site_name: MkLorum
extra_javascript: 
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
docs_dir: _markdown
  
markdown_extensions:
    - math
    - sane_lists
    
theme: readthedocs


